### PR TITLE
x11: Support XRandR versions older than 1.5

### LINKED ISSUE #392: No backend is available
Hello! I'm running Debian Jessie 8.10 with kernel 3.16.0-5-amd64. I'm unable to run the examples of winit. I get the following output:

```
~/D/winit (master) » env RUST_BACKTRACE=1 cargo run --example window
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/examples/window`
thread 'main' panicked at 'No backend is available', src/platform/linux/mod.rs:340:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:537
   6: winit::platform::platform::EventsLoop::new
             at src/platform/linux/mod.rs:340
   7: winit::EventsLoop::new
             at src/lib.rs:195
   8: window::main
             at examples/window.rs:4
   9: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  10: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:479
  11: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  12: std::rt::lang_start_internal
             at libstd/panicking.rs:458
             at libstd/panic.rs:358
             at libstd/rt.rs:58
  13: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  14: main
  15: __libc_start_main
  16: <unknown>
```

I'm using nvidia drivers version 340.102 and other X programs work fine. I run awesome WM as window manager and i've tried running glxgears and it runs. I don't understand why winit won't run for me. Any help appreciated.

### PR DESCRIPTION
**Pull request by b-r-u**
Fixes #392

Previously, initializing the member `xrandr` of `XConnection` resulted
in a panic when symbols from XRandR version 1.5 were missing. There was
already code to handle older versions of XRandR but it was never
executed because of the panic.

The member `XConnection.xrandr` now contains only functions that can
safely be used with older versions. Additionally, this commit adds a new
member to `XConnection` of type `Option<ffi::XRandr>` that only contains
a value if version 1.5 functionality is present. These newer functions are all
related to the handling of monitors and are exclusively used in the
`get_available_monitors` function.

### CODE REVIEW

File: src/platform/linux/x11/xdisplay.rs [hunk 1]
```diff
@@ -10,7 +10,8 @@ use super::ffi;
 /// A connection to an X server.
 pub struct XConnection {
     pub xlib: ffi::Xlib,
-    pub xrandr: ffi::Xrandr,
+    pub xrandr: ffi::Xrandr_2_2_0,
+    pub xrandr_1_5: Option<ffi::Xrandr>,
```
Comment (tomaka) [inline src/platform/linux/x11/xdisplay.rs]: Could you add some comment specifying that the first member concerns XRandr < 1.5 and the second one concerns XRandr >= 1.5? The names and types are a bit confusing otherwise.

**Comment by tomaka** [comment]
Thanks!
