### PR TITLE
Windows: Fix detection of Pause and Scroll keys

### LINKED ISSUE #524: VirtualKeyCode::Pause not recognized when Ctrl is held down, on Windows 8.1
When I press Pause, it looks like this:
```
KeyboardInput { scancode: 69, state: Pressed, virtual_keycode: Some(Pause), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } }
```
When I press Ctrl, then Pause, then release Pause, then release Ctrl, it looks like this:
```
KeyboardInput { scancode: 29, state: Pressed,  virtual_keycode: Some(RControl), modifiers: ModifiersState { shift: false, ctrl: true, alt: false, logo: false } }
KeyboardInput { scancode: 70, state: Pressed,  virtual_keycode: None, modifiers: ModifiersState { shift: false, ctrl: true, alt: false, logo: false } }
KeyboardInput { scancode: 70, state: Released, virtual_keycode: None, modifiers: ModifiersState { shift: false, ctrl: true, alt: false,logo: false } }
KeyboardInput { scancode: 29, state: Released, virtual_keycode: Some(RControl), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } }
```
As you can see, when Ctrl is held down, Pause has a different scancode (70 instead of 69), so it doesn't recognize it as `VirtualKeyCode::Pause`, but it should.

(Btw, for some reason I also get scancode 70 when I press Ctrl + Scroll.)

### PR DESCRIPTION
**Pull request by francesca64**
Fixes #524 

Those looking for a detailed explanation of the problem can read this enjoyable blog post: https://blog.molecular-matters.com/2011/09/05/properly-handling-keyboard-input/

### CODE REVIEW

File: src/platform/windows/events_loop.rs [hunk 1]
```diff
@@ -586,46 +586,48 @@ pub unsafe extern "system" fn callback(window: HWND, msg: UINT,
...
+        winuser::WM_KEYUP | winuser::WM_SYSKEYUP => {
+            use events::ElementState::Released;
+            if let Some((scancode, vkey)) = process_key_params(wparam, lparam) {
                 send_event(Event::WindowEvent {
                     window_id: SuperWindowId(WindowId(window)),
                     event: WindowEvent::KeyboardInput {
                         device_id: DEVICE_ID,
                         input: KeyboardInput {
-                            state: Pressed,
+                            state: Released,
```
Comment (francesca64) [inline src/platform/windows/events_loop.rs]: This has to be the most misleading git diff I've ever seen...
